spring:
  application:
    name: todo-app
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    username: sa
    url: "jdbc:h2:mem:todoapp;DB_CLOSE_ON_EXIT=FALSE"
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
